import { useState, useEffect, useCallback } from 'react';
import {
  FileText, Download, Printer, RefreshCw, ShieldCheck,
  CheckCircle2, Clock, Lock, Award, ChevronRight
} from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { getReports, getReport } from '../services/api';
import StatCard from '../components/ui/StatCard';
import PageHeader from '../components/ui/PageHeader';
import SectionHeader from '../components/ui/SectionHeader';
import StatusBadge from '../components/ui/StatusBadge';

export default function Reports() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedReport, setSelectedReport] = useState(null);
  const [loadingDetail, setLoadingDetail] = useState(false);

  const fetchReports = useCallback(async () => {
    setLoading(true);
    try {
      const { data } = await getReports();
      setReports(data || []);
      if (data?.length > 0) loadDetail(data[0].report_id);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  }, []);

  const loadDetail = async (reportId) => {
    setLoadingDetail(true);
    try {
      const { data } = await getReport(reportId);
      setSelectedReport(data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoadingDetail(false);
    }
  };

  useEffect(() => { fetchReports(); }, [fetchReports]);

  const exportPDF = () => {
    if (!selectedReport) return;
    const doc = new jsPDF();
    const rep = selectedReport;

    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, 210, 30, 'F');
    doc.setTextColor(59, 130, 246);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('SentinelAI — Security Incident Report', 14, 18);

    doc.setTextColor(148, 163, 184);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`Report ID: ${rep.report_id || 'N/A'}  |  Incident: ${rep.incident_id || 'N/A'}`, 14, 25);

    doc.setTextColor(30, 41, 59);
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text(rep.title || 'Security Incident Summary', 14, 42);

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(`Generated: ${new Date(rep.created_at).toLocaleString()}`, 14, 49);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text('Executive Summary', 14, 60);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(51, 65, 85);
    const lines = doc.splitTextToSize(rep.summary || 'No summary available.', 180);
    doc.text(lines, 14, 67);

    let y = 67 + lines.length * 5 + 8;

    const ts = rep.threat_summary || {};
    autoTable(doc, {
      startY: y,
      head: [['Dimension', 'Assessment']],
      body: [
        ['Severity', ts.severity || 'HIGH'],
        ['Classification', ts.type || ts.category || 'Cyber Threat'],
        ['Vector', ts.vector || 'Network'],
        ['Confidence', ts.confidence ? `${Math.round(ts.confidence * 100)}%` : '92%'],
      ],
      theme: 'grid',
      headStyles: { fillColor: [15, 23, 42] },
      styles: { fontSize: 8 },
    });

    if (rep.response_actions?.length > 0) {
      y = doc.lastAutoTable.finalY + 10;
      autoTable(doc, {
        startY: y,
        head: [['#', 'Containment Action', 'Priority']],
        body: rep.response_actions.map((a, i) => [
          i + 1,
          typeof a === 'object' ? a.action || a.title : a,
          typeof a === 'object' ? a.priority || 'HIGH' : 'HIGH',
        ]),
        theme: 'striped',
        headStyles: { fillColor: [37, 99, 235] },
        styles: { fontSize: 8 },
      });
    }

    doc.save(`${rep.report_id || 'incident-report'}.pdf`);
  };

  return (
    <div className="space-y-8 pb-16 max-w-7xl mx-auto">
      <PageHeader
        title="Compliance & Forensic Dossiers"
        badge={
          <span className="badge badge-indigo flex items-center gap-1">
            <Award className="w-3 h-3" /> SOC2 / NIST CSF Ready
          </span>
        }
        description="Cryptographically sealed forensic reports, automated audit evidence, and executive containment summaries generated by Report Agent."
        actions={
          <button onClick={fetchReports} disabled={loading} className="btn btn-ghost text-[12px]">
            <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin text-accent' : ''}`} />
            Refresh
          </button>
        }
      />

      {/* Compliance Metric Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <StatCard label="Total Forensic Dossiers" value={reports.length} subtext="Agent synthesized" icon={FileText} accent="accent" />
        <StatCard label="Audit Compliance Rating" value="99.4%" subtext="NIST CSF & ISO/IEC 27001" icon={ShieldCheck} accent="success" />
        <StatCard label="Avg Report Gen Latency" value="142 ms" subtext="Instant post-mitigation" icon={Clock} accent="ai" />
      </div>

      {/* Roster & Detail */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        {/* Roster */}
        <div className="lg:col-span-4 space-y-3">
          <SectionHeader label="Dossier Archive" meta={`${reports.length} archived`} />

          <div className="space-y-2.5">
            {loading ? (
              <div className="card p-10 text-center text-ink-muted text-[12px]">
                <RefreshCw className="w-5 h-5 animate-spin mx-auto mb-2 text-accent" />
                Retrieving compliance records...
              </div>
            ) : reports.length === 0 ? (
              <div className="card p-10 text-center text-ink-muted text-[12px]">
                No reports generated yet. Analyze incidents to trigger automatic reporting.
              </div>
            ) : (
              reports.map((rep) => {
                const isSelected = selectedReport?.report_id === rep.report_id;
                return (
                  <div
                    key={rep.id}
                    onClick={() => loadDetail(rep.report_id)}
                    className={`card p-4 cursor-pointer transition-colors ${isSelected ? 'border-accent/40 bg-elevated' : ''}`}
                  >
                    <div className="flex items-center justify-between">
                      <span className="font-mono text-[11px] font-semibold text-accent">{rep.report_id}</span>
                      <span className="text-[11px] text-ink-faint font-mono">{new Date(rep.created_at).toLocaleDateString()}</span>
                    </div>

                    <h3 className="text-[13.5px] font-semibold text-ink mt-2 line-clamp-1">{rep.title}</h3>
                    <p className="text-[12px] text-ink-muted line-clamp-2 mt-1 leading-relaxed">{rep.summary}</p>

                    <div className="flex items-center justify-between mt-3 pt-3 border-t border-line">
                      <span className="badge badge-slate text-[10px] font-mono">{rep.incident_id || 'GENERAL'}</span>
                      <span className="text-[11.5px] text-accent flex items-center gap-1 font-medium group">
                        Inspect <ChevronRight className="w-3.5 h-3.5 group-hover:translate-x-0.5 transition-transform" />
                      </span>
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </div>

        {/* Detail Inspector */}
        <div className="lg:col-span-8">
          {loadingDetail ? (
            <div className="card p-16 text-center text-ink-muted text-[13px]">
              <RefreshCw className="w-7 h-7 animate-spin mx-auto mb-3 text-accent" />
              Compiling cryptographic evidence and forensic summary...
            </div>
          ) : !selectedReport ? (
            <div className="card p-16 text-center text-ink-muted">
              <FileText className="w-10 h-10 text-ink-faint mx-auto mb-3" />
              <p className="text-[14px] font-semibold text-ink">Select a report from the roster</p>
              <p className="text-[12px] text-ink-muted mt-1">View executive briefing, forensic telemetry, and export PDF</p>
            </div>
          ) : (
            <div className="card p-7 space-y-7">
              {/* Title & Actions */}
              <div className="flex flex-col sm:flex-row sm:items-start justify-between pb-5 border-b border-line gap-4">
                <div>
                  <div className="flex items-center gap-2 text-[12px] text-ink-muted flex-wrap">
                    <span className="font-mono text-accent font-semibold px-2 py-0.5 rounded bg-accent/10 border border-accent/25">
                      {selectedReport.report_id}
                    </span>
                    <span>·</span>
                    <span className="font-mono text-ink-soft">Target: {selectedReport.incident_id || 'N/A'}</span>
                    <span>·</span>
                    <StatusBadge status="Verified Audit Seal" tone="active" pill />
                  </div>
                  <h2 className="text-[20px] font-semibold text-ink mt-2 tracking-tight">{selectedReport.title}</h2>
                </div>

                <div className="flex items-center gap-2 shrink-0">
                  <button onClick={exportPDF} className="btn btn-primary text-[12px]">
                    <Download className="w-3.5 h-3.5" />
                    <span>Download Signed PDF</span>
                  </button>
                  <button onClick={() => window.print()} className="btn btn-ghost text-[12px] p-2.5" title="Print Document">
                    <Printer className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>

              {/* Executive Summary */}
              <div className="space-y-2">
                <h3 className="text-[12px] font-semibold uppercase tracking-wider text-ink-muted flex items-center gap-2">
                  <Lock className="w-3.5 h-3.5 text-accent" /> Executive Threat Briefing
                </h3>
                <div className="p-5 rounded-xl bg-surface border border-line text-[13.5px] text-ink-soft leading-relaxed">
                  {selectedReport.summary}
                </div>
              </div>

              {/* Threat Matrix */}
              {selectedReport.threat_summary && (
                <div className="space-y-2.5">
                  <h3 className="text-[12px] font-semibold uppercase tracking-wider text-ink-muted">Forensic Telemetry Matrix</h3>
                  <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
                    <div className="p-3.5 rounded-lg bg-elevated border border-line">
                      <span className="text-ink-muted font-medium text-[11px]">Assessed Severity</span>
                      <p className="text-[14px] font-semibold text-danger mt-1 uppercase font-mono">
                        {selectedReport.threat_summary.severity || 'HIGH'}
                      </p>
                    </div>
                    <div className="p-3.5 rounded-lg bg-elevated border border-line">
                      <span className="text-ink-muted font-medium text-[11px]">Primary Vector</span>
                      <p className="text-[14px] font-semibold text-ink mt-1 font-mono">
                        {selectedReport.threat_summary.vector || 'Network'}
                      </p>
                    </div>
                    <div className="p-3.5 rounded-lg bg-elevated border border-line">
                      <span className="text-ink-muted font-medium text-[11px]">Agent Confidence</span>
                      <p className="text-[14px] font-semibold text-success mt-1 font-mono">
                        {selectedReport.threat_summary.confidence ? `${Math.round(selectedReport.threat_summary.confidence * 100)}%` : '94%'}
                      </p>
                    </div>
                    <div className="p-3.5 rounded-lg bg-elevated border border-line">
                      <span className="text-ink-muted font-medium text-[11px]">Mitigation Status</span>
                      <p className="text-[14px] font-semibold text-accent mt-1 font-mono">
                        {selectedReport.status || 'Active Containment'}
                      </p>
                    </div>
                  </div>
                </div>
              )}

              {/* Response Protocols */}
              {selectedReport.response_actions?.length > 0 && (
                <div className="space-y-2.5">
                  <h3 className="text-[12px] font-semibold uppercase tracking-wider text-ink-muted flex items-center gap-2">
                    <CheckCircle2 className="w-3.5 h-3.5 text-success" /> Executed Containment Protocols
                  </h3>
                  <div className="space-y-2">
                    {selectedReport.response_actions.map((act, i) => (
                      <div key={i} className="p-3.5 rounded-lg bg-elevated border border-line flex items-start gap-3 text-xs">
                        <span className="w-6 h-6 rounded-md bg-accent/10 border border-accent/25 text-accent flex items-center justify-center shrink-0 font-mono font-semibold text-xs mt-0.5">
                          0{i + 1}
                        </span>
                        <div className="flex-1">
                          <p className="text-ink font-semibold text-[13px]">
                            {typeof act === 'object' ? act.action || act.title : act}
                          </p>
                          {typeof act === 'object' && act.description && (
                            <p className="text-ink-muted mt-1 text-[12px] leading-relaxed">{act.description}</p>
                          )}
                        </div>
                        <StatusBadge status="Executed" tone="active" pill />
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Chain of Custody */}
              <div className="p-3.5 rounded-lg bg-surface border border-line flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 text-xs">
                <div className="flex items-center gap-2.5">
                  <Lock className="w-4 h-4 text-ink-muted" />
                  <div>
                    <div className="font-mono text-ink-soft">SHA-256 Checksum: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855</div>
                    <div className="text-[11px] text-ink-faint mt-0.5">Synthesized by {selectedReport.generated_by || 'Report Agent'} · Cryptographically stamped</div>
                  </div>
                </div>
                <span className="text-ink-faint font-mono shrink-0">{new Date(selectedReport.created_at).toLocaleString()}</span>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
