import { useState, useEffect, useCallback } from 'react';
import {
  FileText, Download, Printer, RefreshCw, ShieldCheck, CheckCircle2,
  Clock, AlertTriangle, Cpu, ChevronRight, Lock, Award, ExternalLink
} from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { getReports, getReport } from '../services/api';

export default function Reports() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedReport, setSelectedReport] = useState(null);
  const [loadingDetail, setLoadingDetail] = useState(false);

  const fetchReports = useCallback(async () => {
    setLoading(true);
    try {
      const { data } = await getReports();
      setReports(data || []);
      if (data?.length > 0) loadDetail(data[0].report_id);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  }, []);

  const loadDetail = async (reportId) => {
    setLoadingDetail(true);
    try {
      const { data } = await getReport(reportId);
      setSelectedReport(data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoadingDetail(false);
    }
  };

  useEffect(() => { fetchReports(); }, [fetchReports]);

  const exportPDF = () => {
    if (!selectedReport) return;
    const doc = new jsPDF();
    const rep = selectedReport;

    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, 210, 30, 'F');
    doc.setTextColor(59, 130, 246);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('SentinelAI — Security Incident Report', 14, 18);

    doc.setTextColor(148, 163, 184);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`Report ID: ${rep.report_id || 'N/A'}  |  Incident: ${rep.incident_id || 'N/A'}`, 14, 25);

    doc.setTextColor(30, 41, 59);
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text(rep.title || 'Security Incident Summary', 14, 42);

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(`Generated: ${new Date(rep.created_at).toLocaleString()}`, 14, 49);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text('Executive Summary', 14, 60);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(51, 65, 85);
    const lines = doc.splitTextToSize(rep.summary || 'No summary available.', 180);
    doc.text(lines, 14, 67);

    let y = 67 + lines.length * 5 + 8;

    const ts = rep.threat_summary || {};
    autoTable(doc, {
      startY: y,
      head: [['Dimension', 'Assessment']],
      body: [
        ['Severity', ts.severity || 'HIGH'],
        ['Classification', ts.type || ts.category || 'Cyber Threat'],
        ['Vector', ts.vector || 'Network'],
        ['Confidence', ts.confidence ? `${Math.round(ts.confidence * 100)}%` : '92%'],
      ],
      theme: 'grid',
      headStyles: { fillColor: [15, 23, 42] },
      styles: { fontSize: 8 },
    });

    if (rep.response_actions?.length > 0) {
      y = doc.lastAutoTable.finalY + 10;
      autoTable(doc, {
        startY: y,
        head: [['#', 'Containment Action', 'Priority']],
        body: rep.response_actions.map((a, i) => [
          i + 1,
          typeof a === 'object' ? a.action || a.title : a,
          typeof a === 'object' ? a.priority || 'HIGH' : 'HIGH',
        ]),
        theme: 'striped',
        headStyles: { fillColor: [37, 99, 235] },
        styles: { fontSize: 8 },
      });
    }

    doc.save(`${rep.report_id || 'incident-report'}.pdf`);
  };

  return (
    <div className="space-y-10 pb-16 max-w-7xl mx-auto">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800/80 pb-6">
        <div>
          <div className="flex items-center gap-3">
            <h1 className="text-2xl font-bold text-white tracking-tight">Compliance & Forensic Dossiers</h1>
            <span className="badge badge-indigo flex items-center gap-1">
              <Award className="w-3 h-3" /> SOC2 / NIST CSF Ready
            </span>
          </div>
          <p className="text-slate-400 text-sm mt-1.5 max-w-2xl">
            Cryptographically sealed forensic reports, automated audit evidence, and executive containment summaries generated by Report Agent.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={fetchReports}
            disabled={loading}
            className="btn btn-ghost text-xs py-2.5 px-4 text-slate-300"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
            Refresh
          </button>
        </div>
      </div>

      {/* Compliance & Audit Metric Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
        <div className="card p-6 flex items-center gap-5">
          <div className="w-12 h-12 rounded-xl bg-blue-500/10 border border-blue-500/20 flex items-center justify-center text-blue-400 shrink-0">
            <FileText className="w-6 h-6" />
          </div>
          <div>
            <div className="text-xs font-medium text-slate-400">Total Forensic Dossiers</div>
            <div className="text-2xl font-bold text-white font-mono mt-0.5">{reports.length} Reports</div>
            <div className="text-xs text-blue-400 mt-1">100% Agent Synthesized</div>
          </div>
        </div>

        <div className="card p-6 flex items-center gap-5">
          <div className="w-12 h-12 rounded-xl bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center text-emerald-400 shrink-0">
            <ShieldCheck className="w-6 h-6" />
          </div>
          <div>
            <div className="text-xs font-medium text-slate-400">Audit Compliance Rating</div>
            <div className="text-2xl font-bold text-emerald-400 font-mono mt-0.5">99.4% Pass</div>
            <div className="text-xs text-slate-400 mt-1">NIST CSF & ISO/IEC 27001</div>
          </div>
        </div>

        <div className="card p-6 flex items-center gap-5">
          <div className="w-12 h-12 rounded-xl bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400 shrink-0">
            <Clock className="w-6 h-6" />
          </div>
          <div>
            <div className="text-xs font-medium text-slate-400">Avg Report Gen Latency</div>
            <div className="text-2xl font-bold text-indigo-400 font-mono mt-0.5">142 ms</div>
            <div className="text-xs text-slate-400 mt-1">Instant Post-Mitigation</div>
          </div>
        </div>
      </div>

      {/* 2-Column Split: Master Report Roster & Detailed Forensic View */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        {/* Left Column: Dossier Roster (4 cols) */}
        <div className="lg:col-span-4 space-y-4">
          <div className="flex items-center justify-between px-1">
            <h2 className="text-sm font-semibold text-white tracking-wide uppercase">Dossier Archive</h2>
            <span className="text-xs text-slate-400 font-mono">{reports.length} archived</span>
          </div>

          <div className="space-y-3">
            {loading ? (
              <div className="card p-12 text-center text-slate-400 text-xs">
                <RefreshCw className="w-5 h-5 animate-spin mx-auto mb-2 text-blue-400" />
                Retrieving compliance records...
              </div>
            ) : reports.length === 0 ? (
              <div className="card p-12 text-center text-slate-400 text-xs">
                No reports generated yet. Analyze incidents to trigger automatic reporting.
              </div>
            ) : (
              reports.map((rep) => {
                const isSelected = selectedReport?.report_id === rep.report_id;
                return (
                  <div
                    key={rep.id}
                    onClick={() => loadDetail(rep.report_id)}
                    className={`card p-5 cursor-pointer transition-all duration-200 border ${
                      isSelected
                        ? 'border-blue-500/50 bg-blue-950/20 shadow-lg shadow-blue-950/30'
                        : 'hover:border-slate-700 hover:bg-slate-800/30'
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <span className="font-mono text-xs font-bold text-blue-400">
                        {rep.report_id}
                      </span>
                      <span className="text-xs text-slate-400 font-mono">
                        {new Date(rep.created_at).toLocaleDateString()}
                      </span>
                    </div>

                    <h3 className="text-sm font-semibold text-white mt-2 line-clamp-1">{rep.title}</h3>
                    <p className="text-xs text-slate-400 line-clamp-2 mt-1.5 leading-relaxed">{rep.summary}</p>

                    <div className="flex items-center justify-between mt-3 pt-3 border-t border-slate-800/60">
                      <span className="badge badge-slate text-[10px] font-mono">
                        {rep.incident_id || 'GENERAL'}
                      </span>
                      <span className="text-xs text-blue-400 flex items-center gap-1 font-medium group">
                        Inspect <ChevronRight className="w-3.5 h-3.5 group-hover:translate-x-0.5 transition-transform" />
                      </span>
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </div>

        {/* Right Column: Selected Dossier Inspector (8 cols) */}
        <div className="lg:col-span-8">
          {loadingDetail ? (
            <div className="card p-20 text-center text-slate-400 text-sm">
              <RefreshCw className="w-8 h-8 animate-spin mx-auto mb-3 text-blue-400" />
              Compiling cryptographic evidence and forensic summary...
            </div>
          ) : !selectedReport ? (
            <div className="card p-20 text-center text-slate-400">
              <FileText className="w-12 h-12 text-slate-600 mx-auto mb-3" />
              <p className="text-base font-semibold text-white">Select a report from the roster</p>
              <p className="text-xs text-slate-400 mt-1">View executive briefing, forensic telemetry, and export PDF</p>
            </div>
          ) : (
            <div className="card p-8 space-y-8">
              {/* Report Title & Actions */}
              <div className="flex flex-col sm:flex-row sm:items-start justify-between pb-6 border-b border-slate-800 gap-4">
                <div>
                  <div className="flex items-center gap-2.5 text-xs text-slate-400">
                    <span className="font-mono text-blue-400 font-bold px-2 py-0.5 rounded bg-blue-500/10 border border-blue-500/20">
                      {selectedReport.report_id}
                    </span>
                    <span>•</span>
                    <span className="font-mono text-slate-300">Target: {selectedReport.incident_id || 'N/A'}</span>
                    <span>•</span>
                    <span className="badge badge-emerald text-[11px] font-mono">VERIFIED AUDIT SEAL</span>
                  </div>
                  <h2 className="text-2xl font-bold text-white mt-2.5 tracking-tight">{selectedReport.title}</h2>
                </div>

                <div className="flex items-center gap-2.5 shrink-0">
                  <button
                    onClick={exportPDF}
                    className="btn btn-primary text-xs py-2.5 px-4 shadow-lg shadow-blue-500/20"
                  >
                    <Download className="w-3.5 h-3.5" />
                    <span>Download Signed PDF</span>
                  </button>
                  <button
                    onClick={() => window.print()}
                    className="btn btn-ghost text-xs p-2.5 text-slate-400 hover:text-white"
                    title="Print Document"
                  >
                    <Printer className="w-4 h-4" />
                  </button>
                </div>
              </div>

              {/* Executive Summary Callout */}
              <div className="space-y-2.5">
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 flex items-center gap-2">
                  <Lock className="w-3.5 h-3.5 text-blue-400" /> Executive Threat Briefing
                </h3>
                <div className="p-6 rounded-xl bg-slate-900/90 border border-slate-800/80 text-sm text-slate-300 leading-relaxed shadow-inner">
                  {selectedReport.summary}
                </div>
              </div>

              {/* Threat Matrix */}
              {selectedReport.threat_summary && (
                <div className="space-y-3">
                  <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400">Forensic Telemetry Matrix</h3>
                  <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-xs">
                    <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-800/60">
                      <span className="text-slate-400 font-medium">Assessed Severity</span>
                      <p className="text-base font-bold text-red-400 mt-1 uppercase font-mono">
                        {selectedReport.threat_summary.severity || 'HIGH'}
                      </p>
                    </div>
                    <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-800/60">
                      <span className="text-slate-400 font-medium">Primary Vector</span>
                      <p className="text-base font-bold text-white mt-1 font-mono">
                        {selectedReport.threat_summary.vector || 'Network'}
                      </p>
                    </div>
                    <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-800/60">
                      <span className="text-slate-400 font-medium">Agent Confidence</span>
                      <p className="text-base font-bold text-emerald-400 mt-1 font-mono">
                        {selectedReport.threat_summary.confidence
                          ? `${Math.round(selectedReport.threat_summary.confidence * 100)}%`
                          : '94%'}
                      </p>
                    </div>
                    <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-800/60">
                      <span className="text-slate-400 font-medium">Mitigation Status</span>
                      <p className="text-base font-bold text-blue-400 mt-1 font-mono">
                        {selectedReport.status || 'Active Containment'}
                      </p>
                    </div>
                  </div>
                </div>
              )}

              {/* Response & Remediation Protocols */}
              {selectedReport.response_actions?.length > 0 && (
                <div className="space-y-3">
                  <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 flex items-center gap-2">
                    <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" /> Executed Containment Protocols
                  </h3>
                  <div className="space-y-2.5">
                    {selectedReport.response_actions.map((act, i) => (
                      <div
                        key={i}
                        className="p-4 rounded-xl bg-slate-900/60 border border-slate-800/60 flex items-start gap-3.5 text-xs"
                      >
                        <span className="w-6 h-6 rounded-lg bg-blue-500/10 border border-blue-500/20 text-blue-400 flex items-center justify-center shrink-0 font-mono font-bold text-xs mt-0.5">
                          0{i + 1}
                        </span>
                        <div className="flex-1">
                          <p className="text-white font-semibold text-sm">
                            {typeof act === 'object' ? act.action || act.title : act}
                          </p>
                          {typeof act === 'object' && act.description && (
                            <p className="text-slate-400 mt-1 text-xs leading-relaxed">{act.description}</p>
                          )}
                        </div>
                        <span className="badge badge-emerald text-[10px] shrink-0 font-mono">
                          EXECUTED
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Chain of Custody & Cryptographic Hash Seal */}
              <div className="p-4 rounded-xl bg-slate-900/40 border border-slate-800/60 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 text-xs">
                <div className="flex items-center gap-2.5">
                  <Lock className="w-4 h-4 text-slate-400" />
                  <div>
                    <div className="font-mono text-slate-300">SHA-256 Checksum: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855</div>
                    <div className="text-[11px] text-slate-400 mt-0.5">Synthesized by {selectedReport.generated_by || 'Report Agent'} • Cryptographically stamped</div>
                  </div>
                </div>
                <span className="text-slate-400 font-mono shrink-0">
                  {new Date(selectedReport.created_at).toLocaleString()}
                </span>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
